language: go

go:
  - "1.12"

sudo: true
install:
  - dep ensure

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

script:
  - dep ensure && GO_ENABLED=1 go build -v -x -tags "pam" && go install

before_deploy:
  - dep ensure -v && CGO_ENABLED=1 GOARCH=amd64 GOOS=linux go build -o mindoc_linux_amd64 -ldflags="-w -X github.com/mindoc-org/mindoc/conf.VERSION=$TRAVIS_TAG -X 'github.com/mindoc-org/mindoc/conf.BUILD_TIME=`date`' -X 'conf.GO_VERSION=`github.com/mindoc-org/mindoc/go version`'"
  - rm -rf simsun.ttc start.sh commands controllers models modules data routers tasks vendor docs search utils graphics .git Godeps uploads/* .gitignore .travis.yml Dockerfile Gopkg.toml LICENSE main.go README.md conf/enumerate.go conf/mail.go install.lock *.md
  - cp conf/app.conf.example conf/app.conf
  - zip -r mindoc_linux_amd64.zip conf static uploads views lib mindoc_linux_amd64

deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  skip_cleanup: true
  file:
    - mindoc_linux_amd64.zip
  on:
    overwrite: true
    tags: true
    all_branches: true
    go: "1.12"
