# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  name = "github.com/astaxie/beego"
  version = "1.10.0"

[[constraint]]
  name = "github.com/boombuler/barcode"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/service"

[[constraint]]
  name = "github.com/lifei6671/gocaptcha"
  version = "0.1.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/nfnt/resize"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.5.1"

[[constraint]]
  name = "gopkg.in/russross/blackfriday.v2"
  version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true
